package bitbucket

import (
	"fmt"
	"strings"

	"github.com/techitung-arunyawee/code-reviewer-2/internal/review"
)

func ComposeMarkdown(res review.Result) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# AI Code Review Verdict: %s\n\n", res.Verdict.Decision))
	sb.WriteString(fmt.Sprintf("**Model**: %s\n", res.Model))
	sb.WriteString(fmt.Sprintf("**Summary**: %s\n\n", res.Verdict.Summary))

	if len(res.Verdict.Rationale) > 0 {
		sb.WriteString("### Rationale\n")
		for _, r := range res.Verdict.Rationale {
			sb.WriteString(fmt.Sprintf("- %s\n", r))
		}
		sb.WriteString("\n")
	}

	selected := 0
	for _, c := range res.Comments {
		if c.Publish {
			selected++
		}
	}

	if selected > 0 {
		sb.WriteString("## Detailed Comments\n\n")
		for _, c := range res.Comments {
			if !c.Publish {
				continue
			}

			severityBadge := getSeverityBadge(c.Severity)
			sb.WriteString(fmt.Sprintf("### %s %s\n", severityBadge, c.Title))
			sb.WriteString(fmt.Sprintf("**File**: `%s` (lines %d-%d)\n\n", c.FilePath, c.StartLine, c.EndLine))
			sb.WriteString(fmt.Sprintf("%s\n\n", c.Body))

			if c.Suggestion != nil && *c.Suggestion != "" {
				sb.WriteString("**Suggestion**:\n")
				sb.WriteString(fmt.Sprintf("```go\n%s\n```\n\n", *c.Suggestion))
			}

			if c.Evidence != nil && *c.Evidence != "" {
				sb.WriteString("<details><summary>Evidence</summary>\n\n")
				sb.WriteString(fmt.Sprintf("```go\n%s\n```\n", *c.Evidence))
				sb.WriteString("</details>\n\n")
			}
			sb.WriteString("---\n\n")
		}
	}

	sb.WriteString("\n---\n*Generated by AI Code Reviewer*")

	return sb.String()
}

func getSeverityBadge(sev review.Severity) string {
	switch sev {
	case review.SeverityBlocker:
		return "🔴 **BLOCKER**"
	case review.SeverityIssue:
		return "🟠 **ISSUE**"
	case review.SeveritySuggestion:
		return "🟡 **SUGGESTION**"
	case review.SeverityNit:
		return "⚪ **NIT**"
	default:
		return "🔵 **INFO**"
	}
}
